# Generated by Django 4.1.7 on 2023-03-07 11:13

from django.db import migrations


def create_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.create(name='students')
    Group.objects.create(name='instructors')


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')

    Group.objects.get(name='students').delete()
    Group.objects.get(name='instructors').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_groups, delete_groups)
    ]
