# Generated by Django 4.1.7 on 2023-03-07 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_superuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='is_instructor',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
